### ISSUE TITLE
Reference titles with colons cause error

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc#10]
So using a colon in a title is a cardinal sin, I think, but sometimes you need to reference things that have them.

e.g.,

``` yaml
  POODLE:
    target: http://googleonlinesecurity.blogspot.com/2014/10/this-poodle-bites-exploiting-ssl-30.html
    title: This POODLE bites: exploiting the SSL 3.0 fallback
    author:
      name: Bodo Moeller
      ins: B. Moeller
    date: 2014-10-14
```

This produces the wonderfully cryptic:

`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in```parse': (<unknown>): mapping values are not allowed in this context at line 62 column 30 (Psych::SyntaxError)`

Followed by a stack trace, of course.  Compounding this, the colon in question is on line 63 instead.

The only workaround I've found is to rotate the colon 90 degrees..
