### ISSUE TITLE
DOI workarounds for Usenix citations at ACM?

### ISSUE THREAD

**Issue by dkg** [cabo/kramdown-rfc#199]
Usenix papers are published by the ACM, and associated with a DOI reference.  for example, E-Fail is described in https://dl.acm.org/doi/10.5555/3277203.3277245 -- however, a kramdown reference to this DOI number fails because apparently https://doi.org/10.5555/3277203.3277245 doesn't know about it.

I don't know enough about what's going on between DOI and ACM here, but both webservices should be able to produce bibtex.  

i think DOI `10.5555` might be a ["cross-reference" aggregator](https://doi.org/10.5555), maybe the `3277203` segment refers to ACM?  I don't really know.

It would be great if kramdown-rfc could more easily cite usenix papers.

**Comment by cabo** [comment]
It doesn't seem to me that dl.acm.org has an interface like dx.doi.org where I can get application/citeproc+json by setting an Accept header to that.
If you know how to get application/citeproc+json out of dl.acm.org, I could simply switch sites, reacting on the apparently unofficial 10.5555 that ACM uses.

**Comment by cabo** [comment]
Hmm, I don't see how to get that JSON object from the URL you gave, except through a browser.
Do you have a more API-like interface?

Besides, BibTeX is a terrible input format for a conversion.  I'd rather use actual citeproc (hey, that's actually in the name!), or refer ("endnote").  Further hints appreciated.

**Comment by dkg** [comment]
hm, i just fetched it `wget` and had no problem.   what problem did you see? 

It looks like you can vary the `targetFile` and `format` parameters to replace `bibTex` with `endNote`  but i'm not sure how much that changes the data.  it looks like it just modifies the `style` and `suffix` members of the top-level dict, without changing the JSON in `items` at all.  So maybe what's in `items` isn't bibtex, and it's some custom dl.acm.org format?

**Comment by cabo** [comment]
Hmm, wget gives me an empty file.
There is some weird cookie processing going on.

**Comment by cabo** [comment]
This is what my citeproc processor gets out a c/p from a browser:

``` yaml
seriesinfo:
  Proceedings of the 27th USENIX Conference on Security Symposium: pp. 549–566
  DOI:
title: 'Efail: breaking S/MIME and OpenPGP email encryption using exfiltration channels'
author:
- name: Damian Poddebniak
  ins: D. Poddebniak
- name: Christian Dresen
  ins: C. Dresen
- name: Jens Müller
  ins: J. Müller
- name: Fabian Ising
  ins: F. Ising
- name: Sebastian Schinzel
  ins: S. Schinzel
- name: Simon Friedberger
  ins: S. Friedberger
- name: Juraj Somorovsky
  ins: J. Somorovsky
- name: Jörg Schwenk
  ins: J. Schwenk
date: '2018-08-15'
```

Not bad.  What is missing?
