### ISSUE TITLE
doc improvement: add how to construct references to errata reports

### ISSUE THREAD

**Issue by ajeanmahoney** [cabo/kramdown-rfc#221]
In RFCXML, a reference to an errata report is constructed like the following to match the [Web Portion of the Style Guide](https://www.rfc-editor.org/styleguide/part2/#ref_errata):
```
<reference anchor="Err1912" quote-title="false" target="https://www.rfc-editor.org/errata/eid1912"> 
   <front> 
      <title>Erratum ID 1912</title>
      <author>
         <organization>RFC Errata</organization>
      </author> 
   </front> 
   <refcontent>RFC 2978</refcontent>
</reference>
```

Which I think in kramdown-rfc would be specified as:
```
  Err1912:
    target: "https://www.rfc-editor.org/errata/eid1912"
    title: Erratum ID 1912
    author:
    - org: RFC Errata
    refcontent: RFC 4880
    date: false
```

with the caveat that title quotes are not suppressible yet (#182).

Note that refcontent rather than seriesInfo should be used to capture the RFC number (an erratum is not part of the RFC Series). 

I'd be happy to create the PR myself, but I wanted to make sure I had the construction correct first.
