### ISSUE TITLE
Warn about duplicate map keys in YAML? (supporting more than one seriesinfo in a reference entry)

### ISSUE THREAD

**Issue by ajeanmahoney** [cabo/kramdown-rfc#251]
A reference can be in more than one series. For instance, an RFC has an RFC number and a DOI value, and can have a STD or BCP number. ITU-T Recommendations can have both a Recommendation value and an ISO/IEC value:

```
  X.690:
    title: "Information technology - ASN.1 encoding Rules: Specification of Basic Encoding Rules (BER), Canonical Encoding Rules (CER) and Distinguished Encoding Rules (DER)"
    date: 2021-02
    author:
      org: ITU-T
    seriesinfo:
      ITU-T: Recommendation X.690
    seriesinfo:
      ISO/IEC: 8825-1:2021
```

When this is converted to RFCXML, one of the seriesinfo elements is missing:
```
<reference anchor="X.690" >
  <front>
    <title>Information technology - ASN.1 encoding Rules: Specification of Basic Encoding Rules (BER), Canonical Encoding Rules (CER) and Distinguished Encoding Rules (DER)</title>
    <author >
      <organization>ITU-T</organization>
    </author>
    <date year="2021" month="February"/>
  </front>
  <seriesInfo name="ISO/IEC" value="8825-1:2021"/>
</reference>
```

**Comment by cabo** [comment]
```
seriesinfo:
      ITU-T: Recommendation X.690
seriesinfo:
      ISO/IEC: 8825-1:2021
```

The second seriesinfo overwrites the first (unfortunately, the YAML library that kramdown-rfc uses does not detect that).

Please use:

```
seriesinfo:
      ITU-T: Recommendation X.690
      ISO/IEC: 8825-1:2021
```
