### ISSUE TITLE
Overprocesses Date

### ISSUE THREAD

**Issue by CxRes** [cabo/kramdown-rfc#260]
As per RFCXML reference https://authors.ietf.org/rfcxml-vocabulary#date :

> Bibliographic references:
>
> + In order to be able to specify fuzzy dates, such as "2002-2003", "Second quarter 2010", etc., the date element is now permitted to have text content in addition to the year, month, and day attributes. If there is only text content, it will be rendered as is. If there is both text content and date components, both will be rendered, with the expanded date components in parentheses.

However:

```yaml
informative:
  FETCH:
    author:
      -
        ins: A. van Kesteren
        name: Anne van Kesteren
    target: https://fetch.spec.whatwg.org
    title: Fetch
    seriesinfo:
      WHATWG: Living Standard
    date:  Last Updated 28 May 2025
```
 
gets processed as:

```xml
        <reference anchor="FETCH" target="https://fetch.spec.whatwg.org">
          <front>
            <title>Fetch</title>
            <author fullname="Anne van Kesteren" initials="A." surname="van Kesteren">
              <organization/>
            </author>
            <date month="May" year="2025"/>
          </front>
          <seriesInfo name="WHATWG" value="Living Standard"/>
        </reference>
```

There should be a way to specify that date should not be processed when it contains other text. Quoting or block scalars do not help.
